frr defaults traditional
hostname hduflos-routeur1
!
service integrated-vtysh-config
!
! service integrated-vtysh-config : permet de set up tous les daemons dans un seul fichier unifié (celui-ci)
!
line vty
!
