frr defaults traditional
hostname hduflos-routeur_wil-2
service integrated-vtysh-config

interface lo
 ip address 1.1.1.2/32
 ip ospf area 0
!
interface eth0
 ip address 10.1.1.2/30
 ip ospf area 0
!
router bgp 65000
 bgp router-id 1.1.1.2
 no bgp default ipv4-unicast
  advertise-all-vni
 exit-address-family
!
line vty
!
